# Generated by Django 5.0.6 on 2024-05-17 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_articles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlesModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_uz", models.CharField(max_length=255)),
                ("title_ru", models.CharField(max_length=255)),
                ("annotation_uz", models.TextField()),
                ("annotation_ru", models.TextField()),
                ("description_uz", models.TextField()),
                ("description_ru", models.TextField()),
                ("keywords", models.CharField(max_length=255)),
                ("references", models.CharField(max_length=255)),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                ("eye", models.IntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_articles.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
                "db_table": "article",
            },
        ),
    ]
